### ISSUE TITLE
配置不适用于AS4.0

### ISSUE THREAD

**Issue by Lojincen** [githubhaohao/NDK_OpenGLES_3_0#2]
Android Studio4.0已自动打包 CMake 
https://developer.android.google.cn/studio/releases/gradle-plugin#cmake-imported-targets

**Comment by Lojincen** [comment]
把文件夹app\src\main\jniLibs改名为app\src\main\cmakeLibs(or what else but "jniLibs")
在CMakeList.txt里修改对应的行（Modify the corresponding line in CMakeList.txt）
```shell
set(jnilibs "${CMAKE_SOURCE_DIR}/../cmakeLibs")

set_target_properties(assimp PROPERTIES IMPORTED_LOCATION ${CMAKE_SOURCE_DIR}/../cmakeLibs/${ANDROID_ABI}/libassimp.so)

set_target_properties(opencv_java3 PROPERTIES IMPORTED_LOCATION ${CMAKE_SOURCE_DIR}/../cmakeLibs/${ANDROID_ABI}/libopencv_java3.so)
```

**Comment by githubhaohao** [comment]
工程目前的编译环境 AS v4.0 , **NDK r21**。
